apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.12.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: cache
  name: cache
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cache
    spec:
      containers:
      - args:
        - redis-server
        - --appendonly
        - "yes"
        - --requirepass
        - password
        image: redis:3.2-alpine
        name: cache
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: egg-redis
      restartPolicy: Always
      volumes:
      - name: egg-redis
        persistentVolumeClaim:
          claimName: egg-redis
status: {}
