apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.12.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "7001"
    port: 7001
    targetPort: 7001
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
